// default package
// Generated 2016-9-1 20:29:38 by Hibernate Tools 5.1.0.Alpha1

package com.wpr.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TProject generated by hbm2java
 */
@Entity(name = "t_project")
public class TProject implements java.io.Serializable {

	private int id;
	private String projectName;
	private String projectDesc;
	private Set<TReport> TReports = new HashSet<TReport>(0);

	public TProject() {
	}

	public TProject(int id, String projectName) {
		this.id = id;
		this.projectName = projectName;
	}

	public TProject(int id, String projectName, String projectDesc, Set<TReport> TReports) {
		this.id = id;
		this.projectName = projectName;
		this.projectDesc = projectDesc;
		this.TReports = TReports;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "project_name", nullable = false, length = 40)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "project_desc")
	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TProject")
	public Set<TReport> getTReports() {
		return this.TReports;
	}

	public void setTReports(Set<TReport> TReports) {
		this.TReports = TReports;
	}

}
