// default package
// Generated 2016-9-3 20:21:20 by Hibernate Tools 5.1.0.Alpha1

package com.wpr.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TProject generated by hbm2java
 */
@Entity
@Table(name = "t_project", catalog = "wpr")
public class TProject implements java.io.Serializable {

	private Integer id;
	private String projectDesc;
	private String projectName;

	public TProject() {
	}

	public TProject(String projectName) {
		this.projectName = projectName;
	}

	public TProject(String projectDesc, String projectName) {
		this.projectDesc = projectDesc;
		this.projectName = projectName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "project_desc")
	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	@Column(name = "project_name", nullable = false, length = 40)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
