// default package
// Generated 2016-9-3 20:21:20 by Hibernate Tools 5.1.0.Alpha1

package com.wpr.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TReport generated by hbm2java
 */
@Entity
@Table(name = "t_report", catalog = "wpr")
public class TReport implements java.io.Serializable {

	private Integer id;
	private String completed;
	private String plan;
	private String problem;
	private String uncompleted;
	private int projectId;
	private int userId;
	private Date completeTime;

	public TReport() {
	}

	public TReport(int projectId, int userId) {
		this.projectId = projectId;
		this.userId = userId;
	}

	public TReport(String completed, String plan, String problem, String uncompleted, int projectId, int userId) {
		this.completed = completed;
		this.plan = plan;
		this.problem = problem;
		this.uncompleted = uncompleted;
		this.projectId = projectId;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "completed")
	public String getCompleted() {
		return this.completed;
	}

	public void setCompleted(String completed) {
		this.completed = completed;
	}

	@Column(name = "plan")
	public String getPlan() {
		return this.plan;
	}

	public void setPlan(String plan) {
		this.plan = plan;
	}

	@Column(name = "problem")
	public String getProblem() {
		return this.problem;
	}

	public void setProblem(String problem) {
		this.problem = problem;
	}

	@Column(name = "uncompleted")
	public String getUncompleted() {
		return this.uncompleted;
	}

	public void setUncompleted(String uncompleted) {
		this.uncompleted = uncompleted;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}
	@Column(name = "complete_time", nullable = false)
	public Date getCompleteTime() {
		return completeTime;
	}

	public void setCompleteTime(Date completeTime) {
		this.completeTime = completeTime;
	}

}
