// default package
// Generated 2016-9-1 20:29:38 by Hibernate Tools 5.1.0.Alpha1

package com.wpr.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TReport generated by hbm2java
 */
@Entity(name = "t_report" )
public class TReport implements java.io.Serializable {

	private int id;
	private TProject TProject;
	private TUser TUser;
	private String completed;
	private String uncompleted;
	private String problem;
	private String plan;

	public TReport() {
	}

	public TReport(int id, TProject TProject, TUser TUser) {
		this.id = id;
		this.TProject = TProject;
		this.TUser = TUser;
	}

	public TReport(int id, TProject TProject, TUser TUser, String completed, String uncompleted, String problem,
			String plan) {
		this.id = id;
		this.TProject = TProject;
		this.TUser = TUser;
		this.completed = completed;
		this.uncompleted = uncompleted;
		this.problem = problem;
		this.plan = plan;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public TProject getTProject() {
		return this.TProject;
	}

	public void setTProject(TProject TProject) {
		this.TProject = TProject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	@Column(name = "completed")
	public String getCompleted() {
		return this.completed;
	}

	public void setCompleted(String completed) {
		this.completed = completed;
	}

	@Column(name = "uncompleted")
	public String getUncompleted() {
		return this.uncompleted;
	}

	public void setUncompleted(String uncompleted) {
		this.uncompleted = uncompleted;
	}

	@Column(name = "problem")
	public String getProblem() {
		return this.problem;
	}

	public void setProblem(String problem) {
		this.problem = problem;
	}

	@Column(name = "plan")
	public String getPlan() {
		return this.plan;
	}

	public void setPlan(String plan) {
		this.plan = plan;
	}

}
