// default package
// Generated 2016-9-1 20:29:38 by Hibernate Tools 5.1.0.Alpha1

package com.wpr.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TUser generated by hbm2java
 */
@Entity(name = "t_user" )
public class TUser implements java.io.Serializable {

	private int id;
	private String username;
	private String password;
	private Date registTime;
	private Set<TReport> TReports = new HashSet<TReport>(0);

	public TUser() {
	}

	public TUser(int id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
	}

	public TUser(int id, String username, String password, Date registTime, Set<TReport> TReports) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.registTime = registTime;
		this.TReports = TReports;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 40)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "regist_time", length = 19)
	public Date getRegistTime() {
		return this.registTime;
	}

	public void setRegistTime(Date registTime) {
		this.registTime = registTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TUser")
	public Set<TReport> getTReports() {
		return this.TReports;
	}

	public void setTReports(Set<TReport> TReports) {
		this.TReports = TReports;
	}

}
